{% set name = "credible" %}
{% set version = "1.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/credible-{{ version }}.tar.gz
  sha256: 8c92ba3382d9658ca2815494d5a9a3b38448e127be5bd30394514fef454a88f5

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.10
    - setuptools >=61.0.0
    - wheel
    - pip
  run:
    - python >=3.10
    - numpy
    - scipy
    - matplotlib-base
    - scikit-learn

test:
  source_files:
    - tests
  imports:
    - credible
  commands:
    - pip check
    - pytest -sv tests
  requires:
    - pip
    - pytest

about:
  home: https://pypi.org/project/credible/
  doc_url: https://credible.readthedocs.io
  dev_url: https://gitlab.idiap.ch/biosignal/software/credible
  summary: This library contains implementations of some scikit-learn metrics with confidence intervals
  license: GPL-3.0-only
  license_file: LICENSES/GPL-3.0-or-later.txt

extra:
  recipe-maintainers:
    - anjos
